// SPDX-License-Identifier: AGPL-3.0-or-later
// Progress — real numbers per learner: completions, accuracy, active days,
// review load, and per-course bars. For families, classes, co-ops, self-study.
import { useEffect, useState } from "react";
import { api } from "../api";
import { Panel, StatBar, EmptyState } from "../components/ui";

interface ProgressLearner {
  id: number;
  name: string;
  grade_level: number | null;
  attempts_total: number;
  attempts_correct: number;
  active_days: number;
  lessons_done: number;
  reviews_due: number;
  courses: { id: number; title: string; lens: string | null; lessons_total: number; lessons_done: number }[];
}

export default function Progress() {
  const [data, setData] = useState<ProgressLearner[] | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    api<{ learners: ProgressLearner[] }>("/api/progress")
      .then((d) => setData(d.learners))
      .catch(() => setError("Could not load progress."));
  }, []);

  if (error) return <Panel title="Progress"><div className="formerror">{error}</div></Panel>;
  if (!data) return <div className="skel" style={{ height: 180 }} />;

  if (data.length === 0) {
    return (
      <Panel title="Progress & achievements">
        <EmptyState
          icon="📈"
          title="Add learners to start tracking progress"
          message="Once your learners work through courses, you'll see lessons completed, accuracy, active days, and review load here — real numbers, generated by real work."
        />
      </Panel>
    );
  }

  return (
    <>
      {data.map((l) => {
        const accuracy = l.attempts_total ? Math.round((l.attempts_correct / l.attempts_total) * 100) : null;
        return (
          <Panel key={l.id} title={l.name} side={l.grade_level ? `Grade ${l.grade_level}` : undefined}>
            <StatBar
              stats={[
                { label: "Lessons completed", value: l.lessons_done },
                { label: "Answers correct", value: l.attempts_correct },
                { label: "Accuracy", value: accuracy === null ? "—" : `${accuracy}%` },
                { label: "Active days", value: l.active_days },
                { label: "Review due now", value: l.reviews_due, active: l.reviews_due > 0 },
              ]}
            />
            {l.courses.length === 0 ? (
              <p className="muted small">No published courses yet.</p>
            ) : (
              l.courses.map((c) => {
                const pct = c.lessons_total ? Math.round((c.lessons_done / c.lessons_total) * 100) : 0;
                return (
                  <div key={c.id} style={{ marginBottom: 12 }}>
                    <div className="row small" style={{ marginBottom: 4 }}>
                      <span style={{ fontWeight: 600 }}>{c.title}</span>
                      {c.lens && <span className="chip">🧵 {c.lens}</span>}
                      <span className="grow" />
                      <span className="muted">{c.lessons_done}/{c.lessons_total} lessons</span>
                    </div>
                    <div className="progressbar" role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100} aria-label={`${c.title} progress`}>
                      <div style={{ width: `${pct}%` }} />
                    </div>
                  </div>
                );
              })
            )}
          </Panel>
        );
      })}
    </>
  );
}
